/** Generate text for the HTML Text editor AI Placement */
export interface AiplacementEditorGenerateTextParams {
    /** The context ID */
    contextid: number | null;
    /** The prompt text for the AI service */
    prompttext: string | null;
}

export interface AiplacementEditorGenerateTextReturns {
    /** Was the request successful */
    success: boolean | null;
    /** The time the request was created */
    timecreated: number | null;
    /** The prompt text for the AI service */
    prompttext: string | null;
    /** The text generated by AI. */
    generatedcontent?: string | null;
    /** The reason generation was stopped */
    finishreason?: string | null;
    /** Error code if any */
    errorcode?: number | null;
    /** Error message if any */
    error?: string | null;
}

export type AiplacementEditorGenerateTextReturn = AiplacementEditorGenerateTextReturns;
export type aiplacement_editor_generate_text_returns = AiplacementEditorGenerateTextReturns;
