/** Creates an auto-login key for the current user. Is created only in https sites and is restricted by time, ip address and only works if the request comes from the Moodle mobile or desktop app. */
export interface ToolMobileGetAutologinKeyParams {
    /** Private token, usually generated by login/token.php */
    privatetoken: string | null;
}

export interface ToolMobileGetAutologinKeyReturns {
    /** Auto-login key for a single usage with time expiration. */
    key: string | null;
    /** Auto-login URL. */
    autologinurl: string | null;
    /** list of warnings */
    warnings?: Array<{
        /** item */
        item?: string | null;
        /** item id */
        itemid?: number | null;
        /** the warning code can be used by the client app to implement specific behaviour */
        warningcode: string | null;
        /** untranslated english message to explain the warning */
        message: string | null;
    }>;
}

export type ToolMobileGetAutologinKeyReturn = ToolMobileGetAutologinKeyReturns;
export type tool_mobile_get_autologin_key_returns = ToolMobileGetAutologinKeyReturns;
