/** Summarise text for the Course Assistance Placement */
export interface AiplacementCourseassistSummariseTextParams {
    /** The context ID */
    contextid: number | null;
    /** The prompt text for the AI service */
    prompttext: string | null;
}

export interface AiplacementCourseassistSummariseTextReturns {
    /** Was the request successful */
    success: boolean | null;
    /** The time the request was created */
    timecreated: number | null;
    /** The prompt text for the AI service */
    prompttext: string | null;
    /** The text generated by AI. */
    generatedcontent?: string | null;
    /** The reason generation was stopped */
    finishreason?: string | null;
    /** Error code if any */
    errorcode?: number | null;
    /** Error message if any */
    error?: string | null;
}

export type AiplacementCourseassistSummariseTextReturn = AiplacementCourseassistSummariseTextReturns;
export type aiplacement_courseassist_summarise_text_returns = AiplacementCourseassistSummariseTextReturns;
